apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: automated-create-ns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/atulghodmare777/argocd-applications.git"
    path: helm/nginx
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: create-ns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
