apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-7
  namespace: argocd
spec:
  project: project-7
  source:
    repoURL: https://github.com/atulghodmare777/argocd-applications.git
    path: helm/nginx
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

