apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-6
  namespace: argocd
  resourceVersion: "708"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceBlacklist:
  - group: ''
    kind: 'ServiceAccount'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'

