apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-3
  namespace: argocd
  resourceVersion: "708"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'dev'
    server: '*'
  sourceRepos:
  - '*'

